language: python
python:
  - "3.6"

# Install dependencies.
install:
  - pip install -r requirements.txt
  - pip install flake8

# Run linting and tests.
script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics
  - pylint ./src
  - pytest

# Turn email notifications off.
notifications:
  email: false
